name: Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Copy .env
        run: cp Web/.env.example Web/.env

      - name: Composer Install
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          cd Web
          composer update
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: cd Web && php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 Web/storage Web/bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p Web/database
          touch Web/database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: Web/database/database.sqlite
        run: cd Web && vendor/bin/phpunit

      - name: Build Docker image
        run: docker build --tag ps224327 -f Web/Dockerfile .
        # Use -f to specify the location of the Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag ps224327 ${{ secrets.DOCKER_USERNAME }}/ps224327:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ps224327:latest
